### ISSUE TITLE
df_path,macro_path

### ISSUE THREAD

**Issue by tiredDi** [INK-USC/temporal-gcn-lstm#1]
I have some confuse about these two files.
Are they .pkl file?
What are the contents of this file
I will appreciate for your reply.Thanks

**Comment by yozenliu** [comment]
Hi thanks for your interest in the code,
Yes they are .pkl files exported from your Pandas DataFrames.
The contents of these dataframes are listed in the Input dataset comments.
- df_path will be your pandas dataframe .pkl file with the target labels, and if needed you can add in activity sequence data
- macro_path will be your pandas dataframe .pkl file with macroscopic features
When processing data make sure the order of user matches in all dataframes and graph data.

I hope that answers your question!
