### ISSUE TITLE
my silly question

### ISSUE THREAD

**Issue by Bitliuliu** [INK-USC/temporal-gcn-lstm#2]
I'm curious why networkx is already used and dgl is added

**Comment by yozenliu** [comment]
Hey! DGL framework supports message passing which allows us to aggregate neighbor representations and do convolution easily. Our input graphs are in networkx format, but you can of course directly load your graphs into DGLGraph objects!

**Comment by Bitliuliu** [comment]
Thank you for your reply. My recent project involves the joint training of PYG graph neural network and lstm network. I do n’t know if I can discuss it with you.

**Comment by yozenliu** [comment]
Hey sorry I missed this one, you can shoot me an email if it's still relevant!
