### ISSUE TITLE
activity sequence

### ISSUE THREAD

**Issue by danaiz** [INK-USC/temporal-gcn-lstm#3]
Hi, 
In the multi_channel.py module one of the inputs is:
```
Input datasets
    df: dataframe with userid as index, contains labels, and activity sequence if needed
```
I am having trouble to understand how exactly would the activity sequence would look like in a dataframe.
can you maybe provide an example?

thank you!

**Comment by yozenliu** [comment]
Hey,

The df is a 2D dataframe with index as the userid, and a label column. if the activity flag is set, you want to also include columns of the actions you're tracking. Using the paper as an example, these actions will be 'snap send', 'chat send', etc.
each point in these columns contain an array of action counts with length of days observed.  
          ⋅⋅⋅⋅⋅⋅⋅⋅⋅               snap_send ,  chat_send , label
user_id1    [13, 3, 16, 4]  [5, 17, 1, 3]     1
user_id2        ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅      ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅           0

Let me know if this helps or if you have further questions!

**Comment by danaiz** [comment]
thank you!

**Comment by rehamkhawajahere** [comment]
@yozenliu I got about the actions column but can you please tell me how the label is given to each row?
