### ISSUE TITLE
mock_data seem to be empty

### ISSUE THREAD

**Issue by MNFuad** [INK-USC/temporal-gcn-lstm#5]
Thank you so much for sharing these codes. However, I was trying to run the multi_channel.py script. All seem to be okay except that the graph_data in the path "mock_data/example_temporal_user_action_graphs.pkl", when loaded, the graphs are empty (zero nodes).

It could be the way I loaded the nx DiGraphs is not correct,

I have used the following,
```
parser.add_argument('--df_path', type=str,default='mock_data/example_df.pkl')
parser.add_argument('--macro_path', type=str,default='mock_data/example_macro_df.pkl')
parser.add_argument('--graphs_path', type=str,default='mock_data/example_temporal_user_action_graphs.pkl')
```
Then I tried three types of loading pickled graphs:

1 - `graphs_sep = pickle.load(args.graphs_path)`
This gives an error "*** TypeError: file must have 'read' and 'readline' attributes"

2 - `from networkx.readwrite.gpickle import read_gpickle`
`graphs_sep = read_gpickle(args.graphs_path) `
This seems to read the graph dict of [2 x7] correctly. But when converting the nx_graph to dgl, the graphs are empty. *** networkx.exception.NetworkXError: Graph has no nodes or edges

3- 
```
with open(args.graphs_path, 'rb') as f:
        graphs_sep = pickle.load(f)
```
This also correctly reads the graph dict. However, same error is produced. *** networkx.exception.NetworkXError: Graph has no nodes or edges

**Comment by yozenliu** [comment]
Hi, 

Thanks for your interest in our work! 

1 & 3 The pickle loading should be `pickle.load(open(args.graphs_path, 'rb'))` I've pushed a commit to update this.

2 The purpose of the mock data is to give an example of the data input format. It does not serve the purpose of providing any meaningful result. Therefore, the nx graph objects are empty and only demonstrates that each value in the dictionary should contain a sequence of nx graphs. The actual graphs will depend on your specific use case.

That said, I updated the mock data to be able to run `multi_channel.py` without error. Note that the of mock data does not produce meaningful result, and serve the sole purpose of showing an example of input data format.

Hope this helps!

**Comment by MNFuad** [comment]
Many thanks for the swift updates. 
My bad. I was thinking it was not supposed to be empty. So I simulated nx graphs myself and then got stuck with setting the proper net parameters.

However, with your recent updates, it works great.
Thanks again
